services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3030:3030
        depends_on:
            - alloy

    prometheus:
        build:
            context: ./prometheus
            dockerfile: Dockerfile
        user: root
        ports:
            - 9090:9090
        volumes:
            - prometheus_data:/prometheus

    tempo:
        build:
            context: ./tempo
            dockerfile: Dockerfile
        user: root
        ports:
            - 3200:3200 # HTTP server for Tempo
            - 4319:4319 # OTLP receiver
        volumes:
            - tempo_data:/var/tempo

    loki:
        build:
            context: ./loki
            dockerfile: Dockerfile
        user: root
        ports:
            - 3100:3100
        volumes:
            - loki_data:/loki

    grafana:
        build:
            context: ./grafana
            dockerfile: Dockerfile
        user: root
        ports:
            - 3000:3000
        volumes:
            - grafana_data:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_DEFAULT_INSTANCE_NAME=Grafana
            - GF_INSTALL_PLUGINS=grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel

    alloy:
        build:
            context: ./alloy
            dockerfile: Dockerfile
        user: root
        ports:
            - 4317:4317
        volumes:
            - alloy_data:/etc/alloy

volumes:
    prometheus_data:
    tempo_data:
    loki_data:
    grafana_data:
    alloy_data: