apiVersion: 1

prune: false

datasources:
    - name: Loki
      type: loki
      access: proxy
      orgId: 1
      uid: grafana_lokiq
      url: http://loki:3100
      user:
      database:
      basicAuth:
      basicAuthUser:
      withCredentials:
      isDefault: false
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      uid: grafana_prometheus
      url: http://prometheus:9090
      user:
      database:
      basicAuth:
      basicAuthUser:
      withCredentials:
      isDefault: true
    - name: Tempo
      type: tempo
      access: proxy
      orgId: 1
      uid: grafana_tempo
      url: http://tempo:3200
      user:
      database:
      basicAuth:
      basicAuthUser:
      withCredentials:
      isDefault: false